@echo off
echo 🚀 Starting AlgoScribe development...

echo 📦 Starting Go backend...
start cmd /k "cd functions && go run main.go"

echo ⏳ Waiting for backend to start...
timeout /t 3 /nobreak >nul

echo 🎨 Starting Next.js frontend...
cd frontend
call npm run dev
